roboflow_api_key: enter_roboflow_apikey_here  # Robofow API key
video_path: '/Path/To/File/IMG_7139.MOV'  # Path to video file
CLIP:
  # - "bed"
  # - "chair"
  # - "couch"
  # - "wall"
  # - "rug"
  # - "table"
  # - "door"
  # - "stairs"
  # - "television"
  # - "kitchen"
  - wall
  - tile wall
  - large tile wall
  - shower wall
  - shower tiles
  - tiles
  - rectangle shower tile